/// Flutter icons ConfessejaIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ConfessejaIcon
///      fonts:
///       - asset: fonts/ConfessejaIcon.ttf
///
/// 
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
///
import 'package:flutter/widgets.dart';

class ConfessejaIcon {
  ConfessejaIcon._();

  static const _kFontFam = 'ConfessejaIcon';
  static const String _kFontPkg = null;

  static const IconData icone_busca = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData confessor = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData configura__es = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contribuir = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData estrela_amarelo = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_off = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ora__es = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sobre = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData centralizar_mapa = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minhas_confissoes = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData igreja = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData penitente = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
